/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.slayer.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.mpower.slayer.model.InvitationCard;
import com.mpower.slayer.service.InvitationCardLocalServiceUtil;

/**
 * The extended model base implementation for the InvitationCard service. Represents a row in the &quot;mpower_InvitationCard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InvitationCardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvitationCardImpl
 * @see com.mpower.slayer.model.InvitationCard
 * @generated
 */
public abstract class InvitationCardBaseImpl extends InvitationCardModelImpl
	implements InvitationCard {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a invitation card model instance should use the {@link InvitationCard} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			InvitationCardLocalServiceUtil.addInvitationCard(this);
		}
		else {
			InvitationCardLocalServiceUtil.updateInvitationCard(this);
		}
	}
}