package com.fingence;

public interface IConstants {
	int USER_TYPE_INVESTOR = 1;
	int USER_TYPE_WEALTH_ADVISOR = 2;
	int USER_TYPE_BANK_ADMIN = 3;
	int USER_TYPE_REL_MANAGER = 4;
	
	String ROLE_RELATIONSHIP_MANAGER = "Relationship Manager";

	String PAGE_REPORTS_HOME = "Summary";
	String PAGE_ASSET_REPORT = "Asset Report";
	String PAGE_FIXED_INCOME = "Fixed Income";
	String PAGE_RISK_REPORT = "Risk Report";
	String PAGE_PERFORMANCE = "Performance";
	String PAGE_VIOLATIONS = "Violations";
	String ADD_PORTFOLIO = "Add Portfolio";
	String ADD_USER = "Add User";
	
	String PAGE_PORTFOLIO = "Portfolio";
	
	String[] REPORT_MENU_ITEMS = {
		PAGE_REPORTS_HOME,
		PAGE_ASSET_REPORT,
		PAGE_PERFORMANCE,
		PAGE_FIXED_INCOME,
		PAGE_RISK_REPORT,
		PAGE_VIOLATIONS
	};
	
	String PARENT_ORG_FIRMS = "Firms";
	String PARENT_ORG_BANKS = "Banks";
	
	String CMD_CHECK_DUPLICATE = "checkDuplicate";
	String CMD_SET_PORTFOLIO_ID = "setPortfolioId";
	String CMD_SET_ALLOCATION_BY = "setAllocationBy";
	String CMD_CHECK_PORTFOLIO_DUPLICACY = "checkportfolioDuplicacy";
	
	int BREAKUP_BY_RISK_COUNTRY = 1;
	int BREAKUP_BY_CURRENCY = 2;
	int BREAKUP_BY_SECURITY_TYPE = 3;
	int BREAKUP_BY_SECTOR = 4;
	
	String LBL_BREAKUP_BY_RISK_COUNTRY = "Risk Country";
	String LBL_BREAKUP_BY_CURRENCY = "Currency";
	String LBL_BREAKUP_BY_SECURITY_TYPE = "Security Type";
	String LBL_BREAKUP_BY_SECTOR = "Sector";
	
	String THEME_ICON_EDIT = "/common/edit.png";
	String THEME_ICON_DELETE = "/common/delete.png";
	String THEME_ICON_VIEW = "/common/portlet.png";
	
	String CURRENCY_USD = "USD";
	String CURRENCY_UNIT = "1";
	
	String SELECTED = "selected";
	
	//Import Excel
	String EXCEL_SECURITY_TICKER = "Security TICKER";
	String EXCEL_ID_CUSIP = "ID_CUSIP";
	String EXCEL_ID_BB_GLOBAL = "ID_BB_GLOBAL";
	String EXCEL_ID_BB_SEC_NUM_SRC = "ID_BB_SEC_NUM_SRC";
	String EXCEL_NAME = "NAME";
	String EXCEL_CURRENCY = "CRNCY";
	String EXCEL_CHG_PCT_MTD = "CHG_PCT_MTD";
	String EXCEL_CHG_PCT_5D = "CHG_PCT_5D";
	String EXCEL_CHG_PCT_1M = "CHG_PCT_1M";
	String EXCEL_CHG_PCT_3M = "CHG_PCT_3M";
	String EXCEL_CHG_PCT_6M = "CHG_PCT_6M";
	String EXCEL_CHG_PCT_YTD = "CHG_PCT_YTD";
	String EXCEL_BID_PRICE = "PX_BID";
	String EXCEL_ASK_PRICE = "PX_ASK";
	String EXCEL_CHG_PCT_HIGH_52WEEK = "CHG_PCT_HIGH_52WEEK";
	String EXCEL_CHG_PCT_LOW_52WEEK = "CHG_PCT_LOW_52WEEK";
	String EXCEL_INDUSTRY_SECTOR = "INDUSTRY_SECTOR";
	String EXCEL_INDUSTRY_GROUP = "INDUSTRY_GROUP";
	String EXCEL_INDUSTRY_SUBGROUP = "INDUSTRY_SUBGROUP";
	String EXCEL_SECURITY_DES = "SECURITY_DES";
	String EXCEL_SECURITY_TYP = "SECURITY_TYP";
	String EXCEL_SECURITY_TYP2 = "SECURITY_TYP2";
	String EXCEL_PARENT_COMP_NAME = "PARENT_COMP_NAME";
	String EXCEL_SECURITY_CLASS = "BPIPE_REFERENCE_SECURITY_CLASS";
	String EXCEL_VOLATILITY_30D = "VOLATILITY_30D";
	String EXCEL_VOLATILITY_90D = "VOLATILITY_90D";
	String EXCEL_VOLATILITY_180D = "VOLATILITY_180D";
	String EXCEL_VOLATILITY_360D = "VOLATILITY_360D";
	
	String EXCEl_COUNTRY_OF_RISK = "CNTRY_OF_RISK";
	String EXCEl_FUND_NET_ASSET_VALUE = "FUND_NET_ASSET_VAL";
	String EXCEl_ISSUER_BULK = "ISSUER_BULK";
	String EXCEl_CPN = "CPN";
	String EXCEl_CPN_TYP = "CPN_TYP";
	String EXCEl_MTY_TYP = "MTY_TYP";
	String EXCEl_MTY_YEARS_TDY = "MTY_YEARS_TDY";
	String EXCEl_YLD_YTM_ASK = "YLD_YTM_ASK";
	String EXCEl_YLD_YTM_BID = "YLD_YTM_BID";
	String EXCEl_YLD_CUR_MID = "YLD_CUR_MID";
	String EXCEl_BB_COMPOSITE = "BB_COMPOSITE";
	String EXCEl_RTG_SP = "RTG_SP";
	String EXCEl_RTG_MOODY = "RTG_MOODY";
	String EXCEl_CPN_FREQ = "CPN_FREQ";
	String EXCEl_5Y_BID_CDS_SPREAD = "5Y_BID_CDS_SPREAD";
	String EXCEl_DUR_MID = "DUR_MID";
	String EXCEl_PX_TO_CASH_FLOW = "PX_TO_CASH_FLOW";
	String EXCEl_FUND_TOTAL_ASSETS = "FUND_TOTAL_ASSETS";
	String EXCEl_FUND_ASSET_CLASS_FOCUS = "FUND_ASSET_CLASS_FOCUS";
	String EXCEl_FUND_GEO_FOCUS = "FUND_GEO_FOCUS";
	String EXCEl_EQY_ALPHA = "EQY_ALPHA";
	String EXCEl_DIVIDEND_YIELD = "DIVIDEND_YIELD";
	String EXCEl_EQY_DVD_YLD_12M = "EQY_DVD_YLD_12M";
	String EXCEl_EQY_DVD_YLD_EST = "EQY_DVD_YLD_EST";
	String EXCEl_DVD_PAYOUT_RATIO = "DVD_PAYOUT_RATIO";
	
	String EXCEl_EQY_BETA = "EQY_BETA";
	String EXCEl_RETURN_SHARPE_RATIO = "RETURN_SHARPE_RATIO";
	String EXCEl_EQY_SHARPE_RATIO_1YR = "EQY_SHARPE_RATIO_1YR";
	String EXCEl_EQY_SHARPE_RATIO_3YR = "EQY_SHARPE_RATIO_3YR";
	String EXCEl_EQY_SHARPE_RATIO_5YR = "EQY_SHARPE_RATIO_5YR";
	String EXCEl_PE_RATIO = "PE_RATIO";
	String EXCEl_BEST_CURRENT_EV_BEST_OPP = "BEST_CURRENT_EV_BEST_OPP";
	String EXCEl_TRAIL_12M_PROF_MARGIN = "TRAIL_12M_PROF_MARGIN";
	String EXCEl_EBITDA_TO_REVENUE = "EBITDA_TO_REVENUE";
	String EXCEl_TOT_DEBT_TO_COM_EQY = "TOT_DEBT_TO_COM_EQY";
	
}