/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the InvitationCard service. Represents a row in the &quot;mpower_InvitationCard&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mpower.slayer.model.impl.InvitationCardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mpower.slayer.model.impl.InvitationCardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvitationCard
 * @see com.mpower.slayer.model.impl.InvitationCardImpl
 * @see com.mpower.slayer.model.impl.InvitationCardModelImpl
 * @generated
 */
public interface InvitationCardModel extends BaseModel<InvitationCard>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invitation card model instance should use the {@link InvitationCard} interface instead.
	 */

	/**
	 * Returns the primary key of this invitation card.
	 *
	 * @return the primary key of this invitation card
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invitation card.
	 *
	 * @param primaryKey the primary key of this invitation card
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the invitation ID of this invitation card.
	 *
	 * @return the invitation ID of this invitation card
	 */
	public long getInvitationId();

	/**
	 * Sets the invitation ID of this invitation card.
	 *
	 * @param invitationId the invitation ID of this invitation card
	 */
	public void setInvitationId(long invitationId);

	/**
	 * Returns the company ID of this invitation card.
	 *
	 * @return the company ID of this invitation card
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this invitation card.
	 *
	 * @param companyId the company ID of this invitation card
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this invitation card.
	 *
	 * @return the group ID of this invitation card
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this invitation card.
	 *
	 * @param groupId the group ID of this invitation card
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this invitation card.
	 *
	 * @return the user ID of this invitation card
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this invitation card.
	 *
	 * @param userId the user ID of this invitation card
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this invitation card.
	 *
	 * @return the user uuid of this invitation card
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this invitation card.
	 *
	 * @param userUuid the user uuid of this invitation card
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this invitation card.
	 *
	 * @return the user name of this invitation card
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this invitation card.
	 *
	 * @param userName the user name of this invitation card
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this invitation card.
	 *
	 * @return the create date of this invitation card
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this invitation card.
	 *
	 * @param createDate the create date of this invitation card
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this invitation card.
	 *
	 * @return the modified date of this invitation card
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this invitation card.
	 *
	 * @param modifiedDate the modified date of this invitation card
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the invitee email of this invitation card.
	 *
	 * @return the invitee email of this invitation card
	 */
	@AutoEscape
	public String getInviteeEmail();

	/**
	 * Sets the invitee email of this invitation card.
	 *
	 * @param inviteeEmail the invitee email of this invitation card
	 */
	public void setInviteeEmail(String inviteeEmail);

	/**
	 * Returns the status of this invitation card.
	 *
	 * @return the status of this invitation card
	 */
	public int getStatus();

	/**
	 * Sets the status of this invitation card.
	 *
	 * @param status the status of this invitation card
	 */
	public void setStatus(int status);

	/**
	 * Returns the invitee new user ID of this invitation card.
	 *
	 * @return the invitee new user ID of this invitation card
	 */
	public long getInviteeNewUserId();

	/**
	 * Sets the invitee new user ID of this invitation card.
	 *
	 * @param inviteeNewUserId the invitee new user ID of this invitation card
	 */
	public void setInviteeNewUserId(long inviteeNewUserId);

	/**
	 * Returns the invitee new user uuid of this invitation card.
	 *
	 * @return the invitee new user uuid of this invitation card
	 * @throws SystemException if a system exception occurred
	 */
	public String getInviteeNewUserUuid() throws SystemException;

	/**
	 * Sets the invitee new user uuid of this invitation card.
	 *
	 * @param inviteeNewUserUuid the invitee new user uuid of this invitation card
	 */
	public void setInviteeNewUserUuid(String inviteeNewUserUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(InvitationCard invitationCard);

	public int hashCode();

	public CacheModel<InvitationCard> toCacheModel();

	public InvitationCard toEscapedModel();

	public String toString();

	public String toXmlString();
}